Dark mode
Concordium/concordium-browser-wallet pull request #17
Opened 2022-06-07 10:27 UTC by soerenbf

## Purpose

Added dark mode css variables and switch to setup page.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.

2022-06-07 11:14 UTC, shjortConcordium commented
It seems that the dark mode is only enabled after opening the setup page.
(So sign requests are always online)

2022-06-07 12:10 UTC, shjortConcordium requested changes
I assume that this is just for setting up the dark-mode system, seeing as the input fields and buttons don't change.
But please fix the fact that dark mode only starts when entering the setup page! :upside_down_face:

2022-06-07 14:23 UTC, shjortConcordium approved these changes

2022-06-08 07:41 UTC, soerenbf commented on packages/browser-wallet/src/popup/shell/Root.tsx
> +    return <>{children}</>;
Can't do that as we need to return JSX and not a react node.

2022-06-08 08:00 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/shell/Root.tsx
> +    return <>{children}</>;
Hmm :thinking: 
It worked for me.

2022-06-08 09:26 UTC, merged