Add popups before stopping baking/delegation
Concordium/concordium-browser-wallet pull request #299
Opened 2023-04-26 11:33 UTC by shjortConcordium

## Purpose

_Describe the purpose of the pull request, link to issue describing the problem, etc.

## Changes

 - Added popups before stopping baking/delegation.
 - Added a hook for blockchain parameters that only returns the parameters if they are version 1.  

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

2023-04-26 12:56 UTC, orhoj requested changes

2023-04-26 13:26 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/shared/BlockChainParametersProvider.tsx
> + * If the parameters are not version 1, undefined is returned instead.
Yes. :thinking:

2023-04-26 13:43 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/pages/Account/Earn/Delegate/RemoveDelegation.tsx
> +            <Modal open={showModal} disableClose>
I've removed duplication :upside_down_face:

2023-04-27 08:59 UTC, orhoj commented
LGTM

2023-04-27 08:59 UTC, orhoj approved these changes

2023-04-27 12:00 UTC, merged