Create Accounts
Concordium/concordium-browser-wallet pull request #55
Opened 2022-08-19 13:09 UTC by shjortConcordium

## Purpose

Make it possible to create accounts.

## Changes

- Reworked `addAccount` page to actually make accounts.
- Use privateKey from seed.
- Account view handles pending accounts by disabling actions.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2022-08-22 12:48 UTC, orhoj commented
For all accounts it still says `Identity 1` instead of the real name of the associated identity.

2022-08-22 12:49 UTC, orhoj commented
In the identity search drop-down it does not count the number of accounts for the identity, it just says `0 accounts`.

2022-08-22 12:52 UTC, orhoj commented
The account details view has the "confirmed" icon even though finalization is pending.

2022-08-22 14:01 UTC, orhoj requested changes

2022-08-22 14:35 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/pages/AddAccount/AddAccount.scss
> +$add-account-page-arrow-head-size: rem(30px);
nowhere :thinking:

2022-08-22 14:36 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/pages/AddAccount/ChooseIdentity.tsx
> +    const setSelectedIdentityId = useSetAtom(selectedIdentityIdAtom);
It is, but it might be confusing.

2022-08-23 07:45 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/pages/AddAccount/Confirm.tsx
> +            status: IdentityStatus.Pending,
:sweat: I forgot to rename it. It is now CreationStatus, more fitting for the shared use.

2022-08-23 07:46 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/pages/AddAccount/Confirm.tsx
> +                <Button className="add-account-page__confirm-button" type="submit" width="wide" onClick={submit}>
I put a guard in. (But it freezes because of the wasm function, which i'll move to background in the next PR)

2022-08-23 07:47 UTC, shjortConcordium commented on packages/browser-wallet/src/shared/storage/types.ts
> +    identityId: number; // Remove if indexed under it;
I removed it. It was mostly a note that if the credentials are stored as Record<identityId,Credential> there wouldn't be a need for the id to be inside the object as well.

2022-08-23 08:19 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/pages/AddAccount/ChooseIdentity.tsx
> +            {identities
It now shows a link to identity issuance

2022-08-24 07:26 UTC, orhoj commented
I should not be able to edit the name of an identity in the account update creation flow.

2022-08-24 07:31 UTC, orhoj commented
It seems that if my JSON-RPC requests fails when deploying an account, I still end up with an account in the wallet.

2022-08-24 07:33 UTC, orhoj commented
> For all accounts it still says `Identity 1` instead of the real name of the associated identity.

This is still an issue in the account drop-down search list.

2022-08-24 07:56 UTC, orhoj requested changes

2022-08-24 07:56 UTC, orhoj commented on packages/browser-wallet/src/popup/pages/Account/AccountActions/AccountActions.tsx
> +function Action({ children, to, title, disabled = false, end = false, onClick = undefined }: ActionProps) {
I think you always provide the `disabled` variable, so you don't need to provide a default value.

2022-08-24 07:56 UTC, orhoj commented on packages/browser-wallet/src/popup/pages/AddAccount/ChooseIdentity.tsx
> +    const setSelectedIdentityId = useSetAtom(selectedIdentityIdAtom);
Let's just keep it for now.

2022-08-24 09:08 UTC, orhoj approved these changes

2022-08-24 09:17 UTC, merged