Mov/extensioncommunication
Concordium/concordium-browser-wallet pull request #6
Opened 2022-05-05 09:11 UTC by movccd

## Purpose

_Describe the purpose of the pull request, link to issue describing the problem, etc.

## Changes

_Describe the changes that were needed.

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [ ] I accept the above linked CLA.

2022-05-05 14:02 UTC, soerenbf requested changes
Here is some stuff to look into:

- [ ] Remove prettierconfig from `.eslintrc.js`
- [ ] Use yarn to manage workspace dependencies, so we all use the same yarn.lock file
- [ ] Make sure there are no lint errors in the project. Try running `npx eslint_d . --ext .ts,.tsx --max-warnings 0` from the repository root.

Problems I ran into:

- Content script is not executing. Getting an error in the "Errors" page for the extension inside google chrome. As such, it's not possible to test the functionality, as nothing is injected onto the page. Maybe we can look into this together?
  - For some reason it works now... unpacked extensions seem to be a bit unstable.. getting weird errors once in a while that require restarting chrome or some other workaround.

2022-05-05 14:30 UTC, soerenbf reviewed
Couldn't add to my existing review, so here comes a 2nd one.

Some things I find weird from trying to use the message-hub:

- When publishing messages, I have to construct messages, declaring who the message is from. Why is this not given from the message handler used (f.x. all messages from the background handler will have to = backgroundScript)? would be easier to use the handlers if they contained factories for building a message for that particular script.
- There's a lot of setup outside of constructing the message handler. Why is this not just part of the constructor? Makes it hard to 
  - `contentMesageHandler.addWindowPostMessageEventListemer()`
  - `contentMesageHandler.createPortAndSetupEventListeners()`
- Would be easier to subscribe to messages, if it didn't go through the `EventEmitter` interface, as I need to specify an arbitrary event type (string), which can be anything I guess?

2022-05-05 14:30 UTC, soerenbf commented on packages/browser-wallet-message-hub/src/message-handlers/abstract-messagehandler.ts
> +    public async onPortMessage(message: Message, port: chrome.runtime.Port): Promise<void> {
Why is this public? Will I ever need this as a consumer of the API?

2022-05-05 14:30 UTC, soerenbf commented on packages/browser-wallet-message-hub/src/message-handlers/message.ts
> +        public payload: any
Should be optional, as messages without payloads can be valid (f.x. init)

```suggestion
        public payload?: any
```

2022-05-05 20:29 UTC, movccd commented on packages/browser-wallet-message-hub/src/message-handlers/abstract-wallet-messagehandler.ts
> +    public addRuntimePortListeners(): void {
I havent added any JSDoc yet as this is WIP. We would probably end up rewriting JSDoc several times before nailing it. But if doing JSDoc on prelim stuff is standard - I will certainly do it.


The operation is exposed to make it more explicit in the "client" code.

2022-05-05 20:32 UTC, movccd commented on packages/browser-wallet-api/src/wallet-api.ts
> +class WalletApi extends EventEmitter implements IWalletApi {
Consumers are not intended to create instance. There should be only one instance which should be assigned to window.concordium

2022-05-05 20:54 UTC, movccd commented on packages/browser-wallet-message-hub/src/message-handlers/messagetype-enum.ts
> +    event = 'EventMessage',
will be fixed to PascalCase - all the way through

2022-05-05 21:03 UTC, movccd commented on packages/browser-wallet-api/src/wallet-api.ts
> +}, 5000);
agree

2022-05-06 06:23 UTC, soerenbf commented on packages/browser-wallet-message-hub/src/message-handlers/abstract-wallet-messagehandler.ts
> +    public addRuntimePortListeners(): void {
I think the simpler we can make the public API of these message handlers, the better. Ideally, I'd want to:

- Create an instance
- Subscribe to messages + send response to message
- Remove subscription(s)
- Publish message

In my world, only these 4 things should pop up as things to do when i try to access the public API.

2022-05-06 06:46 UTC, soerenbf commented on packages/browser-wallet-message-hub/src/message-handlers/messagetype-enum.ts
> +    event = 'EventMessage',
The `HandlerEnum` is also camelCased, so remember to change that as well then :wink:

2022-05-09 11:35 UTC, soerenbf approved these changes

2022-05-09 11:35 UTC, merged