Update UI for sendTransaction
Concordium/concordium-browser-wallet pull request #76
Opened 2022-09-05 12:26 UTC by shjortConcordium

## Purpose

Update the view for signing transaction from a dApp.

## Changes

Changed FullScreenLayout.
Refactored parts of Account page to use components other places.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2022-09-07 08:15 UTC, orhoj requested changes

2022-09-07 08:15 UTC, orhoj commented on packages/browser-wallet/src/popup/pages/Account/ConnectedBox.tsx
> + * N.B. It is assumed that onNavigate is only given when the box has a link. If link is not provided, then onNavigate is ignored.
It would be preferable to make a type that couples `{ link, onNavigate }` together as a pair, so that you don't need this disclaimer.

2022-09-07 08:15 UTC, orhoj commented on packages/browser-wallet/src/popup/page-layouts/MainLayout/i18n/da.ts
> +        request: 'Signatur anmodning',
```suggestion
        request: 'Signaturanmodning',
```
or Anmodning om signatur.

2022-09-07 08:44 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/page-layouts/MainLayout/i18n/da.ts
> +        request: 'Signatur anmodning',
Anmodning om signatur it is.

2022-09-07 09:04 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/pages/SendTransaction/SendTransaction.tsx
> +                <div>{t('description', { dApp: displayUrl(url) })}</div>
Not if you don't hack it.

2022-09-07 11:08 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/pages/SendTransaction/SendTransaction.tsx
> +                        {transactionType === AccountTransactionType.SimpleTransfer && (
I made a view of it. But we will need more specific handling for something like translations, and maybe some transaction types have more complex fields, that won't stringify properly.

2022-09-07 11:48 UTC, shjortConcordium commented on packages/browser-wallet/src/popup/pages/SendTransaction/SendTransaction.tsx
> +                        {t('error')}: {error}
I made it make a toast.

2022-09-08 12:01 UTC, orhoj requested changes

2022-09-08 12:01 UTC, orhoj commented on packages/browser-wallet/src/popup/shared/i18n/da.ts
> +                simple: 'Send Ccd',
```suggestion
                simple: 'Send CCD',
```

2022-09-08 12:01 UTC, orhoj commented on packages/browser-wallet/src/popup/shared/i18n/en.ts
> +                simple: 'Send Ccd',
```suggestion
                simple: 'Send CCD',
```

2022-09-08 13:28 UTC, shjortConcordium commented
> The buttons should be as in Figma, i.e. at the bottom of the screen. When signing a transfer they are not placed correctly.

I won't do it (I've done it with a "helper" I'll introduce in the update for the signMessage)

2022-09-09 07:45 UTC, orhoj approved these changes

2022-09-09 07:48 UTC, merged